//! Generates a multi-day travel itinerary and provides intelligent responses for related questions.
//!
//! # Modules
//!
//! The module contains the following two primary asynchronous functions:
//! - [`create_plan`]: Generates a detailed travel plan based on a destination and number of days.
//! - [`chat`]: Responds to specific questions about the generated travel plan.
//!
//! # Dependencies
//!
//! This module relies on the following:
//! - [`serde`](https://serde.rs/): For serialization and deserialization of JSON data.
//! - [`worker`](https://developers.cloudflare.com/workers/): For handling HTTP requests and environment management in Cloudflare Workers.
//!
//! ```rust
//! use serde_json::json;
//! use worker::wasm_bindgen::__rt::IntoJsResult;
//! use worker::*;
//! use serde::Deserialize;
//! ```
//!
//! # Structs
//!
//! The module defines the following structs:
//! - [`CfAiResponse`]: Represents the structured JSON response from Cloudflare AI service, containing a `CfAiResult` field.
//! - [`CfAiResult`]: Holds the actual AI-generated response string.
use serde_json::json;
use worker::wasm_bindgen::__rt::IntoJsResult;
use worker::*;
use serde::Deserialize;

/// Represents the response structure from a Cloudflare AI service.
///
/// The `CfAiResponse` struct is designed to deserialize JSON responses
/// from the Cloudflare AI service. It contains the `result` field that
/// holds the main content of the response.
///
/// # Attributes
///
/// * `result` - A `CfAiResult` structure that encapsulates the actual result or data returned from the service.
///
/// # Derives
/// * `Deserialize` - Automatically implements deserialization behavior for transforming
/// JSON data into an instance of `CfAiResponse`.
///
/// # Example
/// ```rust
/// use serde_json::from_str;
///
/// let json_data = r#"
/// {
///     "result": {
///         // result fields here
///     }
/// }
/// "#;
///
/// let response: CfAiResponse = from_str(json_data).expect("Failed to deserialize");
/// ```
#[derive(Deserialize)]
struct CfAiResponse {
    result: CfAiResult,
}

/// A struct representing the result from a Cloudflare AI response.
///
/// This struct is used to deserialize the response from Cloudflare AI
/// into a structured format. The response typically includes a single
/// string field, which contains the output generated by the AI.
///
/// # Fields
/// - `response` (`String`): The response generated by Cloudflare AI.
///
/// # Examples
/// ```
/// use serde::Deserialize;
///
/// #[derive(Deserialize)]
/// struct CfAiResult {
///     response: String,
/// }
///
/// let json_data = r#"{"response": "sample AI output"}"#;
/// let result: CfAiResult = serde_json::from_str(json_data).unwrap();
/// assert_eq!(result.response, "sample AI output");
/// ```
#[derive(Deserialize)]
struct CfAiResult {
    response: String,
}
/// Asynchronously generates a multi-day travel itinerary for a specified destination.
///
/// # Arguments
///
/// * `env` - A reference to the environment object (`Env`) that contains configuration values such as Cloudflare Account ID, AI model, and API tokens.
/// * `destination` - A reference to a `String` representing the destination for the travel plan.
/// * `days` - A `u32` representing the number of days for which the trip should be planned.
///
/// # Returns
///
/// This function returns a `Result` containing:
/// - A tuple:
///   1. A detailed concatenated travel itinerary (`String`) where each day's plan is separated by a newline.
///   2. A summary description (`String`) about the trip plan.
/// - Or an error if the operation fails at any stage (e.g., environment variable not found, API request failure, etc.).
///
/// # Behavior
///
/// - The function builds a travel itinerary by interacting with Cloudflare's AI service (specified by `AI_MODEL` in the environment variables).
/// - For each day in the range from `1` to `days`, it sends a request to an AI service with a structured prompt to generate an itinerary for that specific day.
/// - The API response is parsed, and the generated daily plan is appended to a cumulative itinerary.
/// - The authorized AI request is made using:
///   - A Cloudflare Account ID (`CF_ACCOUNT_ID` from environment variables).
///   - An API token (`CF_API_TOKEN` stored securely in environment secrets).
///   - The AI model specified and the structured prompt for itinerary generation.
///
/// # Environment Variables
///
/// The function depends on the following environment variables:
/// - `CF_ACCOUNT_ID` (Required): The Cloudflare Account ID used to identify the user.
/// - `CF_API_TOKEN` (Required): A secure API token for authentication.
/// - `AI_MODEL` (Optional, defaults to "@cf/meta/llama-3.1-8b-instruct-fast"): The AI model to run for generating the travel itinerary.
///
/// # Errors
///
/// The function returns an error in the following scenarios:
/// - Fails to retrieve required environment variables or secrets (`Env` access issues).
/// - HTTP requests to the Cloudflare AI service fail (e.g., non-200 response codes, network issues).
/// - HTTP response parsing errors when processing the AI response data.
///
/// # Example
///
/// ```rust
/// use your_crate::{create_plan};
/// use your_crate::env::Env;
///
/// #[tokio::main]
/// async fn main() {
///     let env = Env::new();
///     let destination = "Paris".to_string();
///     let days = 3;
///
///     match create_plan(&env, &destination, days).await {
///         Ok((itinerary, summary)) => {
///             println!("Generated Itinerary:\n{}", itinerary);
///             println!("Summary:\n{}", summary);
///         }
///         Err(e) => {
///             eprintln!("Failed to generate trip plan: {}", e);
///         }
///     }
/// }
/// ```
///
/// # Notes
///
/// - The AI prompt enforces that the response includes only an itinerary in a structured format with no additional content.
/// - Each API call is logged per day (e.g., "Day X of Y done").
pub async fn create_plan(env: &Env, destination: &String, days: u32) -> Result<(String, String)> {
    let account_id = env.var("CF_ACCOUNT_ID")?.to_string();
    let model = env
        .var("AI_MODEL")
        .map(|v| v.to_string())
        .unwrap_or("@cf/meta/llama-3.1-8b-instruct-fast".to_string());

    let url = format!("https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/run/{model}");
    let token = env.secret("CF_API_TOKEN")?.to_string();
    let mut plan: Vec<String> = vec![];

    for i in 1..days+1 {
        let body = json!({
        "prompt": format!(
            "You are a travel planner. Continue planning a {days}-day trip to {destination}. \
             Here are the plans for the previous day of your trip:{}
             Now write the itinerary for Day {i}.
             Do not add anything except for the plan. All you need is the time of day, name of the place, and a short one to two sentence description of the place",plan.join("\n")
        ),
    }).to_string();
        console_log!("Day {i} of {days} done");
        let mut init = RequestInit::new();
        init.with_method(Method::Post);
        init.with_body(Some(body.clone().into_js_result()?));

        let mut req = Request::new_with_init(&url, &init)?;
        req.headers_mut()?.set("Authorization", &format!("Bearer {token}"))?;
        req.headers_mut()?.set("Content-Type", "application/json")?;
        req.headers_mut()?.set("Accept", "application/json")?;

        let mut resp = Fetch::Request(req).send().await?;
        if resp.status_code() != 200 {
            return Err(format!("Failed to create plan with error {}", resp.status_code()).into());
        }

        let parsed: CfAiResponse = resp.json().await?;
        plan.push(parsed.result.response);
    }

    Ok((plan.join("\n"), format!("You are a trip planner. Plan a fun and engaging trip to {destination} for {days} days.")))
}
/// Asynchronously handles a chat request for a trip planning AI service.
///
/// # Arguments
///
/// * `env` - A reference to the environment (`Env`) that provides configuration values and secrets such as 
///   account ID, model name, and API token.
/// * `plan` - A reference to a string containing the pre-planned trip information.
/// * `body` - A vector of tuples where each tuple consists of three `String` values representing additional
///   context that may assist the AI in responding to the question.
/// * `question` - A reference to a string containing a user's question about the trip plan.
///
/// # Returns
///
/// Returns a `Result<String>`:
/// * `Ok(String)` - On success, it contains the AI-generated response to the question.
/// * `Err(String)` - On failure, it contains a descriptive error message.
///
/// # Details
///
/// This function:
/// 1. Retrieves the Cloudflare account ID (`CF_ACCOUNT_ID`) and AI model name (`AI_MODEL`) from the environment.
///    If the `AI_MODEL` is not provided, it defaults to `@cf/meta/llama-3.1-8b-instruct-fast`.
/// 2. Constructs the appropriate URL for the Cloudflare AI API based on the account ID and model.
/// 3. Obtains the API token (`CF_API_TOKEN`) securely from the environment.
/// 4. Prepares the API request payload in JSON format, which includes:
///    - A prompt describing the function of the AI as a trip planner.
///    - The user's question.
///    - Context supplied via the `body` parameter.
/// 5. Builds the HTTP request with the required headers (e.g., Authorization, Content-Type).
/// 6. Sends the HTTP request asynchronously using the `Fetch` API and waits for the response.
/// 7. Parses the response as JSON into a `CfAiResponse` type and extracts the AI's result.
///
/// # Errors
///
/// The function returns an error in the following cases:
/// * If required environment variables (`CF_ACCOUNT_ID` or `CF_API_TOKEN`) cannot be retrieved.
/// * If constructing the HTTP request or serializing the body fails.
/// * If the API response status code is not `200 OK`.
/// * If parsing the response body into the `CfAiResponse` type fails.
///
/// # Example
///
/// ```rust
/// use some_module::chat;
///
/// #[tokio::main]
/// async fn main() {
///     let env = Env::default(); // Example environment setup.
///     let plan = "A 3-day itinerary in Paris.";
///     let body = vec![
///         ("Day 1", "Visit Eiffel Tower", "Morning activity"),
///         ("Day 2", "Louvre Museum tour", "Afternoon activity"),
///     ];
///     let question = "What are the transportation options for Day 2?";
///
///     match chat(&env, plan, body, &question).await {
///         Ok(response) => println!("AI Response: {}", response),
///         Err(e) => eprintln!("Error: {}", e),
///     }
/// }
/// ```
pub async fn chat(env: &Env, plan: &str, body: Vec<(String, String, String)>, question: &String) -> Result<String> {
    let account_id = env.var("CF_ACCOUNT_ID")?.to_string();
    let model = env
        .var("AI_MODEL")
        .map(|v| v.to_string())
        .unwrap_or("@cf/meta/llama-3.1-8b-instruct-fast".to_string());

    let url = format!("https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/run/{model}");
    let token = env.secret("CF_API_TOKEN")?.to_string();

    let body = json!({
        "prompt": format!(
            "You are a trip planner. You have already planned a fun and engaging trip and this is your plan: {plan}. \
             You are asked this question about the trip: {question}. \
             You will be given the following context:"
        ),
        "context": body
    }).to_string();

    let mut init = RequestInit::new();
    init.with_method(Method::Post);
    init.with_body(Some(body.clone().into_js_result()?));

    let mut req = Request::new_with_init(&url, &init)?;
    req.headers_mut()?.set("Authorization", &format!("Bearer {token}"))?;
    req.headers_mut()?.set("Content-Type", "application/json")?;
    req.headers_mut()?.set("Accept", "application/json")?;

    let mut resp = Fetch::Request(req).send().await?;
    if resp.status_code() != 200 {
        return Err(format!("Failed to create plan with error {}", resp.status_code()).into());
    }

    let parsed: CfAiResponse = resp.json().await?;
    Ok(parsed.result.response)
}